[build.nixpacksPlan.phases.install]
cmds = ["apt-get install -y npm"]

[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT=9191